{
    "name": "Custom Payment Voucher",
    "version": "1.0",
    "category": "Accounting",
    "summary": "Manage Receipt Vouchers for Payments",
    "description": "A module to handle receipt vouchers for payments in Odoo.",
    "author": "Onestone Software LLP",
    "depends": ['base','account'],
    "data": [
        "security/ir.model.access.csv",
        'data/email_template.xml',
        'data/cron_data.xml',
        'data/groups.xml',
        'data/data_sequence.xml',
        'views/payment_voucher_views.xml',
        'views/view_payment_voucher_breakdown.xml',
        'views/res_company_views.xml',
        'views/res_users_views.xml',
        'wizards/view_approval_comment_wizard.xml',
        'reports/report_template.xml',
    ],
    'images': ['static/description/icon.png'],
    "license": "LGPL-3",
    "installable": True,
    "application": True,
}
